dag: true

steps:
  - id: "lint"
    name: ":bash: Lint"
    command: .buildkite/steps/lint.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - id: "bats-tests"
    name: ":bash: Unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v2.1.0:
        run: unit-tests
        config: docker-compose.unit-tests.yml

  - id: "s3secrets-helper-linux-amd64"
    name: ":golang: :linux: s3secrets-helper-linux-amd64"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker#v3.7.0:
        image: "golang:1.15"
        mount-checkout: false
        volumes:
          - "./build:/build:rw"
          - "./plugins/secrets/s3secrets-helper:/s3secrets-helper:ro"
        workdir: /s3secrets-helper
        environment:
          - "GOOS=linux"
          - "GOARCH=amd64"
        command: ["go", "build", "-o", "/build/s3secrets-helper-linux-amd64"]
    artifact_paths:
      - build/s3secrets-helper-linux-amd64

  - id: "s3secrets-helper-windows-amd64"
    name: ":golang: :windows: s3secrets-helper-windows-amd64"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker#v3.7.0:
        image: "golang:1.15"
        mount-checkout: false
        volumes:
          - "./build:/build:rw"
          - "./plugins/secrets/s3secrets-helper:/s3secrets-helper:ro"
        workdir: /s3secrets-helper
        environment:
          - "GOOS=windows"
          - "GOARCH=amd64"
        command: ["go", "build", "-o", "/build/s3secrets-helper-windows-amd64.exe"]
    artifact_paths:
      - build/s3secrets-helper-windows-amd64

  - id: "packer-windows"
    name: ":packer: :windows:"
    command: .buildkite/steps/packer.sh windows
    timeout_in_minutes: 60
    retry: { automatic: { limit: 3 } }
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - "lint"
      - "bats-tests"
      - "s3secrets-helper-windows-amd64"

  - id: "windows-launch"
    name: ":cloudformation: :windows: Launch"
    command: .buildkite/steps/launch.sh windows
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"
    depends_on: "packer-windows"

  - id: "windows-test"
    name: ":cloudformation: :windows: Test"
    command: "docker info"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-windows-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-windows-${BUILDKITE_BUILD_NUMBER}"
    depends_on: "windows-launch"

  - id: "packer-linux"
    name: ":packer: :linux:"
    command: .buildkite/steps/packer.sh linux
    timeout_in_minutes: 60
    retry: { automatic: { limit: 3 } }
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - "lint"
      - "bats-tests"
      - "s3secrets-helper-linux-amd64"

  - id: "linux-launch"
    name: ":cloudformation: :linux: Launch"
    command: .buildkite/steps/launch.sh linux
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"
    depends_on: "packer-linux"

  - id: "linux-test"
    name: ":cloudformation: :linux: Test"
    command: "goss validate --format documentation"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-linux-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-linux-${BUILDKITE_BUILD_NUMBER}"
    depends_on: "linux-launch"

  - id: "copy-ami"
    name: ":cloudformation: 🚚 🌎"
    command: .buildkite/steps/copy.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/mappings.yml"
    depends_on:
      - "linux-test"
      - "windows-test"

  - id: "publish"
    name: ":cloudformation: :rocket:"
    command: .buildkite/steps/publish.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    concurrency_group: "aws-stack-publish"
    concurrency: 1
    artifact_paths: "build/*.yml"
    depends_on: "copy-ami"

  - id: "cleanup"
    name: "Cleanup"
    command: .buildkite/steps/cleanup.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on: "publish"
